### PR TITLE
Issue85 fix admin search fn

### PR DESCRIPTION
**Pull request by seg1129**

### CODE REVIEW

**Comment by tjrivera** [comment]
Can you describe which part of the admin search is broken in the BRP? Which model are you searching across?

**Comment by tjrivera** [comment]
Ah, I see. `ProtocolUser` and `ProtocolUserCredential` and `ProtocolDataSource`. Next time, we should add that to the issue.

**Comment by seg1129** [comment]
next time I'll add the exact table I am modifying. The Admin part that this is fixing is preventing the application from crashing when being utilized. Alex F wanted to keep the search function on the page. The other admin search feature issue you see is about properly searching fields that are encrypted. once Django is upgraded I will override the admin search function to search on decrypted values. Since I will be addressing that at a separate time I wanted to keep the issues separate.

**Comment by tjrivera** [comment]
Cool, just wanted to double check. This looks good, search will no longer crash, but it doesn't exactly "work" since it's still search encrypted data.

**Pull request merged**
